# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache
          key: v2-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: npm ci
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: npm ci
      - run: CI=true npm test
      - store_test_results:
          path: test-results

  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: npm ci
      - run:
          name: npm run build
          command: for i in {1..5}; do npm run build && break || sleep 5; done
          environment:
            NODE_OPTIONS: --max_old_space_size=4096

      - persist_to_workspace:
          root: .
          paths:
            - public/*

  e2e:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: npm ci
      - run: npm run test:e2e:ci
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: ~/repo/cypress/snapshots
          destination: snapshots

  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "51:78:3e:67:09:2d:dc:d3:5a:78:0b:3b:a1:1c:6b:44"
      - run: echo 'ertrzyiks.me,104.236.224.189 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBNfW9tfAr21CQlapt944WeYOaSftTQB3Ly/Tm/1ZeXYEI08w9v9FEXRG2E+Sj/EDHimklHLlCwWCPMqMYFMQsMg=' >> ~/.ssh/known_hosts
      - run:
          name: Deployment
          command: |
            git config --global user.email "deploy-bot@ertrzyiks.me"
            git config --global user.name "Deploy Bot"
            cd public
            git init
            git remote add dokku dokku@ertrzyiks.me:yummy
            git add .
            git commit -m 'Update'
            git push dokku master --force

workflows:
  version: 2
  build_deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install

      - build:
          requires:
            - test
      - e2e:
          requires:
            - test

      - deploy:
          requires:
            - e2e
            - build
          filters:
            branches:
              only: master
