# Header
menu:
  Główna: /
  Obiady: /obiady/
  Zupy: /zupy/
  Ciasta: /ciasta/
rss: /atom.xml

# Content
excerpt_link: Pokaż przepis
fancybox: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-114663776-1
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
