# Header
menu:
  Śniadaniowe: /sniadaniowe/
  Obiady: /obiady/
  Zupy: /zupy/
  Ciasta: /ciasta/
  Koktajle: /koktajle/
rss: /atom.xml

# Content
excerpt_link: Pokaż przepis
fancybox: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-114663776-1
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

lqip:
  potrace:
    canvas_size:
      width: 140
    optTolerance: 5
    turdSize: 3
    threshold: 200
    steps: 2
    color: '#ec973b'
    background: 'transparent'
